// <auto-generated />
using System;
using FinanceBot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceBot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508201859_M001_InitialSchema")]
    partial class M001_InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceBot.Infrastructure.Persistence.Entities.ExpenseEntity", b =>
                {
                    b.Property<Guid>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<bool>("AutoConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_confirmed");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("bucket");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_review");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<Guid?>("PlannedId")
                        .HasColumnType("uuid")
                        .HasColumnName("planned_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ExpenseId");

                    b.HasIndex("PeriodId");

                    b.HasIndex("UserId", "OccurredAt");

                    b.HasIndex("UserId", "PeriodId");

                    b.ToTable("expenses", "app");
                });

            modelBuilder.Entity("FinanceBot.Infrastructure.Persistence.Entities.IncomeEntity", b =>
                {
                    b.Property<Guid>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("income_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("IncomeId");

                    b.HasIndex("PeriodId");

                    b.HasIndex("UserId", "PeriodId");

                    b.ToTable("incomes", "app");
                });

            modelBuilder.Entity("FinanceBot.Infrastructure.Persistence.Entities.PeriodEntity", b =>
                {
                    b.Property<Guid>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<decimal>("AllocationDeposit")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("allocation_deposit");

                    b.Property<decimal>("AllocationEssentials")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("allocation_essentials");

                    b.Property<decimal>("AllocationFun")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("allocation_fun");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<decimal?>("SavingsActual")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("savings_actual");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalIncome")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_income");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("PeriodId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("periods", "app");
                });

            modelBuilder.Entity("FinanceBot.Infrastructure.Persistence.Entities.ProjectionOffsetEntity", b =>
                {
                    b.Property<string>("ProjectionName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("projection_name");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_updated");

                    b.Property<long>("OffsetValue")
                        .HasColumnType("bigint")
                        .HasColumnName("offset_value");

                    b.HasKey("ProjectionName");

                    b.ToTable("projection_offsets", "app");
                });

            modelBuilder.Entity("FinanceBot.Infrastructure.Persistence.Entities.SystemHeartbeatEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_seen");

                    b.HasKey("Id");

                    b.ToTable("system_heartbeat", "app", t =>
                        {
                            t.HasCheckConstraint("ck_system_heartbeat_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("FinanceBot.Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_updated");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("registered_at");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings_json");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.HasKey("UserId");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("users", "app");
                });

            modelBuilder.Entity("FinanceBot.Infrastructure.Persistence.Entities.WhitelistEntity", b =>
                {
                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("added_at");

                    b.Property<long>("AddedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("added_by");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.HasKey("TelegramId");

                    b.ToTable("whitelist", "app");
                });

            modelBuilder.Entity("FinanceBot.Infrastructure.Persistence.Entities.ExpenseEntity", b =>
                {
                    b.HasOne("FinanceBot.Infrastructure.Persistence.Entities.PeriodEntity", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceBot.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceBot.Infrastructure.Persistence.Entities.IncomeEntity", b =>
                {
                    b.HasOne("FinanceBot.Infrastructure.Persistence.Entities.PeriodEntity", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceBot.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceBot.Infrastructure.Persistence.Entities.PeriodEntity", b =>
                {
                    b.HasOne("FinanceBot.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
